slikapp/urls.py
from django.conf.urls import patterns, url
from slikapp import views

urlpatterns = patterns('',
	url(r'^slika/(?P<id>\d+)/$', views.slika, name='slika'),
	url(r'^upload', views.UploadCreate.as_view(), name='upload'),
	url(r'^komentar', views.komentar, name='komentar'),
	url(r'^$', views.index, name='index'),
)

styria/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	url(r'^admin/', include(admin.site.urls)),
	url(r'^', include('slikapp.urls', namespace='slikapp')),
)

if settings.DEBUG:
	urlpatterns += patterns('',
		(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}))

slikapp/models.py
from django.db import models

class Slika(models.Model):
	datoteka = models.ImageField(upload_to='slike')
	opis = models.CharField(max_length=200)

	def __unicode__(self):
		return self.opis

class Komentar(models.Model):
	tekst = models.TextField()
	slika = models.ForeignKey(Slika)
	vrijeme = models.DateTimeField(auto_now_add=True)

	def __unicode__(self):
		return self.tekst

slikapp/forms.py
from django import forms
from models import Slika

class UploadForm(forms.ModelForm):
	class Meta:
		model = Slika

slikapp/views.py
from django.shortcuts import get_object_or_404, render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.decorators.csrf import csrf_protect
from django.utils import simplejson
from django.http import HttpResponseRedirect, HttpResponse
from django.views.generic import CreateView
from django.core.urlresolvers import reverse_lazy
from models import Slika, Komentar
from forms import UploadForm


def index(request):
    sve_slike = Slika.objects.all().order_by('-id')
    paginator = Paginator(sve_slike, 16)
    stranica = request.GET.get('stranica')    

    try:
        slike_stranica = paginator.page(stranica)
    except PageNotAnInteger:
        slike_stranica = paginator.page(1)
    except EmptyPage:
        slike_stranica = paginator.page(paginator.num_pages)

    context = {'sve_slike': slike_stranica}
    return render(request, 'slikapp/index.html', context)

class UploadCreate(CreateView):
    model = Slika
    context_object_name = 'datoteka'
    template_name = 'slikapp/upload.html'
    form_class = UploadForm
    success_url = reverse_lazy('slikapp:index')

def slika(request, id):
    slika = get_object_or_404(Slika, pk=id)
    return render(request, 'slikapp/slika.html', {'slika': slika, 'komentari': slika.komentar_set.all()})

@csrf_protect
def komentar(request):
    results = ''
    try:
        if request.method == u'POST':
            if request.POST.has_key(u'pk') and request.POST.has_key(u'tekst'):
                pk = int(request.POST[u'pk'])
                slika = Slika.objects.get(pk=pk)
                kom = slika.komentar_set.create(tekst=request.POST[u'tekst'])
                results = '<li><small>'+ kom.vrijeme.strftime("%c") +'</small><p>'+ kom.tekst +'</p></li>'
    except Slika.DoesNotExist:
        pass
    return HttpResponse(results)

slikapp/templates/slikapp/base.html
{%  load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}{% endblock %} - SlikApp</title>
    
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    
			 <link rel="stylesheet" type="text/css" href="{% static 'slikapp/css/bootstrap.min.css' %}" />
    <script src="{% static 'slikapp/js/jquery-1.10.2.min.js' %}"></script>

</head>
<body>

    <div class="container" style="width: 1000px">
        {% block content %}{% endblock %}
    </div>
    
</body>
</html>

slikapp/templates/slikapp/index.html
{% extends "slikapp/base.html" %}
{% load staticfiles %}

{% block title %}Index{% endblock %}

{% block content %}
	<div class="row-fluid text-center" style="padding-top: 30px;">
		<form class="" method="post" action="/upload/" enctype="multipart/form-data">
				{% csrf_token %}
				<div class="input-append">
	    <input id="id_datoteka" name="datoteka" type="file">
	    <input id="id_opis" maxlength="200" name="opis" type="text" placeholder="Opis slike">
	    <input type="submit" class="btn btn-primary" value="Upload">
	    </div>
		</form>
	</div>
	{% if sve_slike %}
		<div class="row">
	      <ul class="thumbnails">
	          {% for slika in sve_slike %}
		          <li class="span3" >
		              <a href="{% url 'slikapp:slika' slika.id %}" class="thumbnail">
			              	<img src="{{ slika.datoteka.url }}" alt="{{ slika.opis }}" style="max-height: 150px">
			              	<p class="text-center">{{ slika.opis }}</p>
		              </a>
		          </li>
		           {% if forloop.counter|divisibleby:4 %}<div class="clearfix"></div>{% endif %}
	          {% endfor %}
   </div>
  </div>
  
  <div class="row-fluid text-center" style="padding-bottom: 30px">
    <span class="step-links">
        {% if sve_slike.has_previous %}
            <a href="?stranica={{ sve_slike.previous_page_number }}">prethodna</a>
        {% endif %}

        <span class="current">
            {{ sve_slike.number }} / {{ sve_slike.paginator.num_pages }}
        </span>

        {% if sve_slike.has_next %}
            <a href="?stranica={{  sve_slike.next_page_number }}">sljedeća</a>
        {% endif %}
    </span>
  </div>
		
	{% else %}
		    <p>Nema slika :(</p>
	{% endif %}
{% endblock %}

slikapp/templates/slikapp/slika.html
{% extends "slikapp/base.html" %}
{% load staticfiles %}

{% block title %}{{ slika.opis }}{% endblock %}

{% block content %}
<div class="row-fluid" style="padding: 30px 0 30px 0">
	<div class="span12">
	<div class="span6"><img class="featurette-image pull-left" src="{{ slika.datoteka.url }}" alt="{{ slika.opis }}" width="500"></div>
	<div class="span6"><p class="lead">{{ slika.opis }}</p></div>
	</div>
	</div>
	<div class="row-fluid">
		<div class="span6">
			<ul id="komentari">
				{% if komentari %}
					{% for komentar in komentari %}
							<li>
					    <small>{{ komentar.vrijeme }}</small>
					    <p>{{ komentar.tekst }}</p>
					  </li>
					{% endfor %}
				{% else %}
								<li id="nema_komentara">
									<p>Nitko nije komentirao...</p>
								</li>
				{% endif %}
			</ul>
		</div>		
	</div>
	
			<div class="row-fluid">
        <div class="span5">
            <form class="" method="post" action="">
            				{% csrf_token %}
                <textarea id="tekst" rows="3" name="text"></textarea>
                <input type="button" class="btn" value="Komentiraj!">
            </form>
        </div>    
    </div>	
	
	
<script src="{% static 'slikapp/js/csrftoken.js' %}"></script>
<script type="text/javascript" >
				$(".btn").click(function(event) 
				{	
							event.preventDefault();							
							var tekst = $("#tekst").val();
							var slika_id = {{ slika.id }};
							if(tekst==''){
										return false;
							}
							else{
										$.ajax({
												type: "POST",
												url: "/komentar/",
												data: { pk: slika_id, tekst: tekst },
												cache: false,
												success: function(html){
															if($('#nema_komentara').is(':visible')) {
															    $('#nema_komentara').fadeOut('fast');
															}
															$("ul#komentari").append(html);
															$("ul#komentari li:last").fadeIn("slow");
															$("#tekst").val('');
												}
										}).fail(function(jqXHR, textStatus) { $
														alert( "Request failed: " + textStatus );
										});
							}
							return false;
				}); 
</script>
	
{% endblock %}

slikapp/templates/slikapp/upload.html
{% extends "slikapp/base.html" %}
{% load staticfiles %}

{% block title %}Upload{% endblock %}

{% block content %}
	<form class="" method="post" action="" enctype="multipart/form-data">
	{% csrf_token %}
                
	    {% for field in form %}
	        {{ field }}<br />
	    {% endfor %}
	
	    <input type="submit" class="btn btn-primary" value="Pohrani sliku">
	</form>
	
{% endblock %}